theme: jekyll-theme-cayman
title: Gksudo Replacement, GUI open as Root or Other User,for X11 and Wayland, in Plasma, Gnome, XFCE, XFCE, LXQT
google_site_verification: "pDyf2qfswvjxGD1bvfA7GWKQGHVxclgGmXmWL6PD1ZM" 
