#!/bin/bash
####################################################################################
# GKSUDO2-SU. This script is NOT to be run independently and will fail
#	if tried. This secondary script is called by GKSUDO2 for actions requiring
#	elevated (sudo) privileges. Required variable assignments are passed in the 
#	calling statement from GKSUDO2.  Created under GPLv3 license, by
#	William Rueger (furryfixer). Updated 07/2026.
##=================================================================================##

err_exit1 () { 
	if ! dbus-run-session zenity --warning --title="gksudo2 Error" --text="$*" --width 600  &>/dev/null; then
		echo "$*"  # print error without zenity
	fi
	finish_cleanup
	exit 1
}
err_exit_file () {  # $1 is title, $2 is header, $3 is filename
	echo -e "${2}\n$(cat ${3})" > /tmp/gk/err-file-out
	if ps -e | grep -Eq 'Hyprland|sway|niri|river|dwl|qtile' ; then # Wayland tilers may not float --text-info
		if ! dbus-run-session zenity --warning --title="${1}" --text="$(cat /tmp/gk/err-file-out)" --width 600 --no-wrap --no-markup --modal &>/dev/null; then
			cat /tmp/gk/err-file-out  # print error without zenity
		fi
	elif ! dbus-run-session zenity --text-info --title="${1} (scrollable)" --width 600 --height 400 --filename /tmp/gk/err-file-out --no-wrap --no-markup --modal &>/dev/null; then
		cat /tmp/gk/err-file-out  # print error without zenity
	fi
	finish_cleanup
	exit 1
}
cleanup_files_dbus () {
	# Reap dbus-daemons if possible
	if read new_dbus 2>/dev/null < $as_usr_rundir/ps-dbus ; then
		[[ $new_dbus -ne $last_dbus ]] && kill -- -$new_dbus &>/dev/null
	fi
	[[ -f /tmp/gk/kdeglobals ]] && mv /tmp/gk/kdeglobals /root/.config/kdeglobals
}
finish_cleanup () {
	rm -f $xauth_gksudo 
	rm -f /tmp/gk/gk-env-cmd
	rm -f /tmp/gk/sudo.gk.error
	if [[ -d "$as_usr_rundir" ]]; then
		umount "$as_usr_rundir/gvfs" 2> /dev/null
		umount "$as_usr_rundir/doc" 2> /dev/null
		rm -R $as_usr_rundir
	fi
	gk_instances=$(pgrep -c gksudo2-su)
	if [[ $XDG_SESSION_TYPE = "wayland" ]] && [[ $gk_instances -lt 2 ]]; then
		chmod 0700 $orig_xdg_rundir
		chmod 0755 $wayland_socket
	fi
}
######
if [[ -z "$INVOKING_USR" ]]; then
	err_exit1 "STOP! gksudo2-su improperly called, or
attempted to run independently of gksudo2 "
fi
rm -f /tmp/gk/err-file-out
as_usr_rundir=$(mktemp -d /tmp/gk/runtime-gksudo-as-$as_user.XXXX)
chmod 0700 $as_usr_rundir
chown $as_user $as_usr_rundir
xauth_gksudo=$(mktemp /tmp/gk/.gk.XXXXXXX)
[[ -s "$XAUTHORITY" ]] && cp $XAUTHORITY $xauth_gksudo
XAUTHORITY=$xauth_gksudo
chmod 0600 $xauth_gksudo
chown $as_user $xauth_gksudo
if [[ $XDG_SESSION_TYPE = "x11" ]]; then  # X11 Session
	if  ! pgrep Xorg &> /dev/null; then
		echo "STOP! No X11 or Wayland Display Server found for gksudo2" >&2
		exit 1
	fi
	if [ ! -s "$XAUTHORITY" ]; then
		x11_ps=$(ps -C Xorg -o args h)
		cp $(echo ${x11_ps#*auth } | cut -d " " -f 1) $XAUTHORITY
	fi
	if [ ! -s "$XAUTHORITY" ]; then
		err_exit1 "STOP! Unable to find working Xauthority file "
	fi	
	[[ -z "$DISPLAY" ]] && err_exit1 "STOP! \$DISPLAY not set. Xserver inaccessible"

else # WAYLAND SESSION!

	chmod 0755 $orig_xdg_rundir
	if ! (chmod 0777 $wayland_socket); then
		err_exit1 "ERROR! Unable to find or access Wayland Display socket"
	fi
	as_usr_wayland_sock=$as_usr_rundir/wayland-0
	if [ ! -L "$as_usr_wayland_sock" ]; then
		if ! (ln -s $wayland_socket $as_usr_wayland_sock 2>/dev/null); then
			err_exit1 "STOP! Failed to link to Wayland Socket "
		fi
	fi
	# Wayland apps may wrongly set/change $DISPLAY used by Xwayland (e.g. mate-terminal)
	# Reacquire proper $DISPLAY setting
	if pgrep "Xwayland" >/dev/null; then
		pid_xwayland=$(pgrep Xwayland | tail -1)
		DISPLAY=$(ps -ho args $pid_xwayland | cut -d " " -f 2)	
	else
		DISPLAY=$(ps eh -e | grep -m 1 ' WAYLAND_DISPLAY' | sed -rn 's/.* DISPLAY=//p' | cut -d " " -f 1)
	fi
	# Xwayland may need Xauthority for some compositors. Inexact method
	[[ -z "${XAUTHORITY}" && -s "${usr_home}/.Xauthority" ]] && XAUTHORITY="${usr_home}/.Xauthority"
fi
as_usr_home=$(eval echo "~${as_user}")
timestamp=`date +%D" "%H:%M:%S`
program=$@
echo "${timestamp}.  User <${INVOKING_USR}> ran <$program> as user <${as_user}>"  >> /var/log/gksudo2.log
#
echo "#!/bin/bash
   set -a
   . /etc/environment
   cd \"${current_dir}\" 2>/dev/null
   orig_xdg_rundir=\"${orig_xdg_rundir}\"
   DISPLAY=${DISPLAY}
   XAUTHORITY=${xauth_gksudo}
   XDG_SESSION_TYPE=${XDG_SESSION_TYPE}
   XDG_CURRENT_DESKTOP=${XDG_CURRENT_DESKTOP}
   XDG_RUNTIME_DIR=\"${as_usr_rundir}\"
   XDG_CONFIG_HOME=\"${as_usr_home}/.config\"
   WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
   wayland_socket=${wayland_socket}" > /tmp/gk/gk-env-cmd

if grep -q 'konqueror' <<< "$1"  &&  [[ $as_user = "root" ]]; then
## Allow root konqueror but Prevent URL browsing as root
	echo "   QTWEBENGINE_DISABLE_SANDBOX=1" >> /tmp/gk/gk-env-cmd
	mkdir -p /root/.config
	touch /root/.config/kdeglobals		
	if ! grep -q "KDE URL Restrictions" /root/.config/kdeglobals; then
		cp /root/.config/kdeglobals /tmp/gk/kdeglobals
		echo "[KDE URL Restrictions]
rule_count=1
rule_1=open,,,,http,,,false" >> /root/.config/kdeglobals
	fi
fi
# Most Wayland, and some Gnome apps, require dbus-launch with this method.
# dbus-run-session fails, so use dbus-launch and find PID of new dbus-daemon
#    and remove process group later.
if grep -q -E "kate|caja" <<< "$@"; then     # Kate or Caja may immediately background themselves
	dbusl_cmd="   dbus-launch $@"
else
	dbusl_cmd="   dbus-launch $@ &"
fi	
echo "   ${dbusl_cmd}
   ps > /dev/null   # Only to force update of process tree
   pgrep -n dbus-daemon > \${XDG_RUNTIME_DIR}/ps-dbus
   wait \$!" >> /tmp/gk/gk-env-cmd
# Backgrounding dbus-launch allows to get dbus-daemon PID immediately,
#    but this forces use of wait to proceed properly after.
chmod +x /tmp/gk/gk-env-cmd
failed=false
last_dbus=$(pgrep -n dbus-daemon)
if ! sudo -u $INVOKING_USR pkexec --user $as_user /tmp/gk/gk-env-cmd >/tmp/gk/sudo.gk.error 2>&1; then # Failed execution
	cleanup_files_dbus
	failed=true
	if grep -q 'open display' /tmp/gk/sudo.gk.error; then 
		if ! sudo -u $INVOKING_USR xhost | grep -q $as_user ; then  # retry with xhost as last resort 		
			sudo -u $INVOKING_USR xhost SI:localuser:$as_user &>/dev/null
			last_dbus=$(pgrep -n dbus-daemon)
			if sudo -u $INVOKING_USR pkexec --user $as_user /tmp/gk/gk-env-cmd >/tmp/gk/sudo.gk.error 2>&1; then # succeeded
				failed=false
			fi
			cleanup_files_dbus 
			sudo -u $INVOKING_USR xhost -SI:localuser:$as_user &>/dev/null	
		fi
	fi
else
	cleanup_files_dbus 
fi
if $failed ; then	
	if [[ -s /tmp/gk/sudo.gk.error ]]; then  # If no error reported, we will allow to fail silently
		if grep "command as another user" /tmp/gk/sudo.gk.error; then
			err_exit1 "$(tail -n 3 /tmp/gk/sudo.gk.error)"
		else
			sed -E -n -i '/protocol specified|ToQuit/!p' /tmp/gk/sudo.gk.error
			sed -E -n -i '/assertion|isPrimaryInstance|Initializing|QDir|usershare/!p' /tmp/gk/sudo.gk.error
			err_exit_file "gksudo2 Error" "Error! if cryptic, possibly from unclean exit of child process" /tmp/gk/sudo.gk.error
		fi
	fi
elif [[ -s /tmp/gk/sudo.gk.error ]]; then  # succeeded, but check errors/warnings
 	#  Filter some normally superfluous warnings from stderr/stdout
	tail -n 2 /tmp/gk/sudo.gk.error > /tmp/gk/parsed-error 
	if ! grep -E 'uninitialized|exiting|assertion|Bind on socket|isPrimaryInstance|WARNING|kdeinit5|Failed to connect|Initializing|QDir|ToQuit|net usershare|dictionaries|Activat|Success|portal.Error' /tmp/gk/parsed-error; then
		sed -i '/^[[:space:]]*$/d' /tmp/gk/sudo.gk.error
		sed -E -n -i '/dictionaries|protocol specified|ToQuit|WARNING|usershare info/!p' /tmp/gk/sudo.gk.error
		sed -E -n -i '/Gtk-CRITICAL|uninitialized|assertion|isPrimaryInstance|Initializing|QDir|send signal/!p' /tmp/gk/sudo.gk.error
		sed -E -n -i '/Unexpected nullptr|Expected a KPluginFactory|changed|still attached|Shortcut/!p' /tmp/gk/sudo.gk.error
		sed -E -n -i '/context|GpuChannel|GFileInfo|gfileinfo/!p' /tmp/gk/sudo.gk.error
		sed -E -n -i '/QThread|"wayland"|refused|viewproperties/!p' /tmp/gk/sudo.gk.error
		if grep -q '[^[:space:]]' /tmp/gk/sudo.gk.error ; then # if not just white space
			err_exit_file "gksudo2 Warning" "" /tmp/gk/sudo.gk.error
		fi
	fi
fi
finish_cleanup
exit 0
