#!/bin/bash
##########################################################################
# GKSUDO2 Uninstall script, by William Rueger (furryfixer)
# You must run with sudo or as ROOT!
##########################################################################

# user must be root
if [ "$(id -u)" != "0" ]; then
   echo "Uninstall script must be run as root" 1>&2
   exit 1
fi
echo "
This script will remove gksudo2 from your system. Do you wish 
to continue?

Press [Y/N] and <ENTER>."
read yn
[[ $yn != [Yy] ]] && exit 1
echo "
Uninstalling gksudo2...
"
[[ -L /usr/local/bin/gksudo ]] && rm -r -v /usr/local/bin/gksudo
[[ -L /usr/local/bin/gksu ]] && rm -r -v /usr/local/bin/gksu
[[ -L /usr/bin/gksudo ]] && rm -r -v /usr/bin/gksudo
[[ -L /usr/bin/gksu ]] && rm -r -v /usr/bin/gksu
[[ -f /usr/local/bin/gksudo2 ]] && rm -r -v /usr/local/bin/gksudo2
[[ -f /usr/local/bin/gksudo2-su ]] && rm -r -v /usr/local/bin/gksudo2-su
[[ -f /usr/bin/gksudo2 ]] && rm -r -v /usr/bin/gksudo2
[[ -f /usr/bin/gksudo2-su ]] && rm -r -v /usr/bin/gksudo2-su
[[ -f /usr/share/polkit-1/actions/gksudo2.gk.env.cmd.policy ]] && rm -v /usr/share/polkit-1/actions/gksudo2.gk.env.cmd.policy
[[ -f /etc/polkit-1/rules.d/47-gksudo2-gk-env-cmd.rules ]] && rm -v /etc/polkit-1/rules.d/47-gksudo2-gk-env-cmd.rules
[[ -f /usr/local/bin/filemanager-gksudo2 ]] && rm -v /usr/local/bin/filemanager-gksudo2
[[ -f /usr/bin/filemanager-gksudo2 ]] && rm -v /usr/bin/filemanager-gksudo2
echo "
gksudo2 successfully removed.
"
